git:
  depth: 2
sudo: required
services:
- docker
language: node_js
node_js: node
before_install:
- curl -sSL https://get.docker.com/ | sudo sh
- curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname
  -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null && sudo chmod
  +x /usr/local/bin/docker-compose
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
install:
- npm install -g tyche codecov
script:
- yarn
- tyche test
deploy:
  provider: npm
  email: landers.robert@gmail.com
  api_key:
    secure: YREgjiM/VIc1PbIFd6OYsNGI7Gwfeqa3RZxIaKYZF1Y+is7UW48wLQ1FitpJ2dOOkU2dHWgPBoGJOqQWKUNwxRHnSn4kBdMRUXam4PttdOzBGxJukBICPqhAaXxoOkxCsBv2gkKYbMmknzi4YOYxb7Suop5H2HN+Qlh4Nqh+BaGHVb8izleGLzxaETwmiSN7lQ3reLGZCDB/ztH4Pd/gK0oxHip4ISklzVtyaUbuXZjvh8hzWakS7F3urC6sHU6/wOcuZ7Vq+tyqgFSwFKIsiWpvRQ/9WFZw006Kb1NeWD9/kswBldUuWv33yv+0theaSv6HueLU0hw5Yf/QR2Surq6OuPJF2j6tJua5yRXKCRvBu3D9IEGq+4qe9IyOUOrqSzMMvyXKAaawu1AV9SXPdISLb9C74A8XSOn2UOF1eXSNf0lIqQCQaK7ZXvtpUYgjQNnL8yJreHkxNchyeHc6gCdIdq1DyncGu+uMxRZ9IX8Nzy8IAmNcaM4VPfZNWQ/NnuDy/UM1/jztLvnyeaZarQGdcIT5aoOW1aOlz2B7w4A0xuWNYRRendgprtKCNE/C4OMIrPXsdtETreKfuBQSCk7Uhj4+KEzCC9bpzun/Wx1zRzMn2g/OXH+4vC0FFnqHhNNM5C+HkX+NG/RFLLK6SRG3h8mv4yabOBs2uuZi7mo=
  on:
    tags: true
    repo: withinboredom/omniscient-net
